cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:service_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('full_remove/<uuid:service_id>/', views.full_remove, name='full_remove'),
]

contact/urls.py
from django.urls import path
from .views import contact_us, contact_success

app_name = 'contact'

urlpatterns = [
    path('', contact_us, name='contact_us'),
    path('success/', contact_success, name='contact_success'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.orderDetail.as_view(), name='order_detail'),
]

search/urls.py
from django.urls import path
from .views import SearchResultsListView, filterView

app_name = 'search'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='search_result'),
    path('advanced/', filterView, name='advanced_search_result'),
]

servicehireproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('search/', include('search.urls')),
    path('orders/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('conversation/', include('conversations.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.service_list, name = 'all_services'),
    path('<uuid:category_id>/', views.service_list, name = 'services_by_category'),
    path('<uuid:category_id>/<uuid:service_id>/', views.service_detail, name = 'service_detail'),
    path('new/', views.ServiceCreateView.as_view(), name='post_service'),
    path('<uuid:service_id>/edit/', views.ServiceUpdateView.as_view(), name='edit_service'),
    path('<uuid:service_id>/delete/', views.ServiceDeleteView.as_view(), name='delete_service'),
    path('<uuid:service_id>/submit_review/', views.submit_review, name='submit_review'),
    path('provider/', views.provider_service_list, name = 'service_provider'),
]

pages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <!-- Icon -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Font -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
    <!-- Browser Icon-->
    <link rel="icon" href="{% static 'images/tenner_icon32.png' %}">
        <title>{% block title %}{% endblock title %} | Tenner</title>
</head>

<body>
    {% include 'navbar.html' %}

    {% block content%}
    {% endblock content %}

    {% include 'footer.html' %}

    <!-- Scroll Top Button -->
    <button onclick="topFunction()" class="btn" id="scrollTop"><i class="fa fa-angle-up "></i></button>
  
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <!-- Local Script -->
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

pages/templates/footer.html
<footer>
    <div class="container py-4 py-lg-5">
        <div class="row justify-content-center">
            <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Services</h3>
                <ul class="list-unstyled">
                    <li><a href="{% url 'services:all_services' %}">All Services</a></li>
                    {% for category in category_links %}
                        <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">About</h3>
                <ul class="list-unstyled text-muted">
                    <li><a href="#">Company</a></li>
                    <li><a href="{% url 'team' %}">Team</a></li>
                </ul>
            </div>
            <div class="col-sm-4 col-md-3 text-center text-lg-start d-flex flex-column">
                <h3 class="fs-6 fw-bold">Contact</h3>
                <ul class="list-unstyled">
                    <li><a href="{% url 'contact:contact_us' %}">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-lg-3 text-center text-lg-start d-flex flex-column align-items-center order-first align-items-lg-start order-lg-last">
                <h3 class="fs-6 fw-bold">Tenner</h3>
                <p class="text-muted fst-italic mb-4">Year 2 project for Computing with Software Development course from Technological University Dublin - Tallaght.</p>
            </div>
        </div>
        <hr>
        <div class="text-muted d-flex justify-content-between align-items-center pt-3">
            <p class="mb-0">Copyright © {% now 'Y' %} Tenner</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item pt-3">
                    <a href="https://www.facebook.com/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-facebook">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                        </svg>
                    </a>
                </li>
                <li class="list-inline-item pt-3">
                    <a href="https://www.linkedin.com/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16"> <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                        </svg>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://twitter.com/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-twitter">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                        </svg>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.instagram.com/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-instagram">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

pages/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
<main class = "container px-0 mw-100 text-center">
  <div id = "carouselExampleControls" class = "carousel slide carousel-fade" data-bs-ride = "carousel">
      <div class = "carousel-inner">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="0" class="active"></button>
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="1"></button>
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="2"></button>
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="3"></button>
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="4"></button>
          <button type="button" data-bs-target="#carouselExampleControls" data-bs-slide-to="5"></button>
        </div>
        <div class = "carousel-item active" data-bs-interval = "5000">
          <img src = "{% static 'images/signup2day.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-1">
          <div class = "carousel-caption">
            <h3>Sign Up Today</h3>
            <p>Become a service provider in a few easy steps!</p>
            <a class = "btn btn-primary my-3" href = "{% url 'signup' %}">Sign Up</a>
          </div>
        </div>
        {% for category in category_links %}
        {% if category.name == 'Graphics & Design' %}
        <div class = "carousel-item" data-bs-interval = "5000">
          <img src = "{% static 'images/graphicsanddesign.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-2">
          <div class = "carousel-caption">
            <h3>Graphics & Design</h3>
            <a class = "btn btn-primary my-3" href = "{{ category.get_absolute_url }}">Browse Services</a>
          </div>
        </div>
        {% endif %}

        {% if category.name == 'Music & Audio' %}
        <div class = "carousel-item" data-bs-interval = "5000">
          <img src = "{% static 'images/musicandaudio.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-3">
          <div class = "carousel-caption">
            <h3>Music & Audio</h3>
            <a class = "btn btn-primary my-3" href = "{{ category.get_absolute_url }}">Browse Services</a>
          </div>
        </div>
        {% endif %}

        {% if category.name == 'Programming & Tech' %}
        <div class = "carousel-item" data-bs-interval = "5000">
          <img src = "{% static 'images/programmingandtech.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-4">
          <div class = "carousel-caption">
            <h3>Programming & Tech</h3>
            <a class = "btn btn-primary my-3" href = "{{ category.get_absolute_url }}">Browse Services</a>
          </div>
        </div>
        {% endif %} 

        {% if category.name == 'Video & Animation' %}
        <div class = "carousel-item" data-bs-interval = "5000">
          <img src = "{% static 'images/videoandanimation.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-5">
          <div class = "carousel-caption">
            <h3>Video & Animation</h3>
            <a class = "btn btn-primary my-3" href = "{{ category.get_absolute_url }}">Browse Services</a>
          </div>
        </div>
        {% endif %} 

        {% if category.name == 'Writing & Translation' %}
        <div class = "carousel-item" data-bs-interval = "5000">
          <img src = "{% static 'images/writingandtranslation.jpg' %}" class = "d-block w-100 carousel-image" alt = "carousel-6">
          <div class = "carousel-caption">
            <h3>Writing & Translation</h3>
            <a class = "btn btn-primary my-3" href = "{{ category.get_absolute_url }}">Browse Services</a>
          </div>
        </div>
        {% endif %} 
        {% endfor %}
      </div>
      <button class = "carousel-control-prev" type = "button" data-bs-target = "#carouselExampleControls" data-bs-slide = "prev">
        <span class = "carousel-control-prev-icon" aria-hidden = "true"></span>
        <span class = "visually-hidden">Previous</span>
      </button>
      <button class = "carousel-control-next" type = "button" data-bs-target = "#carouselExampleControls" data-bs-slide = "next">
        <span class = "carousel-control-next-icon" aria-hidden = "true"></span>
        <span class = "visually-hidden">Next</span>
      </button>
  </div>
  <br>
  <img class = "mb-3" src = "{% static 'images/tenner_logo7.png' %}" alt = "logo" style = "height: 70px">
  <h3 class="mb-5">The best <span style="font-style: italic; font-weight: bold;">freelance</span> service for you and your business</h3>
  <div class="container my-5">
    <div class="row my-5">
      <div class="col-6">
        <img src = "{% static 'images/landing-1.jpg' %}" class = "mw-100" alt = "landing1">
      </div>
      <div class="col text-start">
        <h3 class = "fw-bold">Hire professionals</h3>
        <p>Tenner is a website that allows you to hire professionals for any digital service you need.</p>
        <p>Develop your business or website with ease with the help of our service providers.</p>
        <p>Check out all of our available services&nbsp;<a class = "link-violet" href = "{% url 'services:all_services' %}">here</a></p>
      </div>
    </div>
    <br>
    <div class = "row my-5">
      <div class = "col-6 text-start">
        <h3 class = "fw-bold">Become a Provider</h3>
        <p>If you are not interested in our services, you might be willing to provide a service instead.</p>
        <p>There are numerous service providers, with varying skill levels and certifications.</p>
        <p>Sign up and become a service provider&nbsp;<a class = "link-violet" href = "{% url 'signup' %}">here</a></p>
      </div>
      <div class="col-6">
        <img src = "{% static 'images/landing-2.jpg' %}" class = "mw-100" alt = "landing2">
      </div>
    </div>
    <br>
    <div class = "row my-5">
      <div class="col-6">
        <img src = "{% static 'images/landing-3.jpg' %}" class = "mw-100" alt = "landing3">
      </div>
      <div class = "col-6 text-start">
        <h3 class = "fw-bold">More Information</h3>
        <p>Meet the&nbsp;<a class = "link-violet" href = "{% url 'team' %}">team</a> who brought this all together!</p>
        <p>If there are any queries or issues with your experience with Tenner, do not hesitate to&nbsp;<a class = "link-violet" href = "{% url 'contact:contact_us' %}">contact us</a></p>
      </div>
    </div>
  </div> 
</main>
{% endblock %}

pages/templates/navbar.html
{% load auth_extras %}
{% load static %}

<nav class="navbar navbar-dark navbar-expand-md sticky-top navbar-shrink py-3" id="mainNav">
    <div class="container">
        <a class = "me-3" href = "/"><img src = "{% static 'images/tenner_logo7.png' %}" class = "w-100 logo-size" alt = "logo"></a>
        <div id="search-bar">
            <form action="{% url 'search:search_result' %}" method="GET" style="width: 100%;">
                <div class="input-group">
                    <input type="search" class="form-control" placeholder="Search for services" aria-label="Search"
                        name="q">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown">Services</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'services:all_services' %}">All Services</a></li>
                            {% for category in category_links %}
                                <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'team' %}">Team</a></li>     
                <li class="nav-item"><a class="nav-link" href="{% url 'contact:contact_us' %}">Contact Us</a></li>
            </ul>

            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <div class="d-flex align-items-center">
                    {% if item_count > 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                            <i class="fas fa-shopping-cart"></i>&nbsp;Cart ({{item_count}})
                    </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                            <i class="fas fa-shopping-cart"></i>&nbsp;Cart
                        </a>
                    </li>
                    {% endif %}
                </div>
                    <li class="nav-item">
                        <li class="nav-item dropdown">
                            {% if user.profile.image %}
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                                <img class="rounded-circle" src="{{ user.profile.image.url }}" width="36px;" alt="User profile image">
                            </a>
                            {% else %}
                            <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown">
                                <img class="rounded-circle" src="{% static 'images/default_profile_pic.jpg' %}" width="36px;" alt="User profile image">
                            </a>
                            {% endif %}
                        <ul class="dropdown-menu"">
                            {% if user|has_group:'Service Provider' %}
                                <li><a class="dropdown-item" href="{% url 'services:service_provider' %}">Your Services</a></li>
                                <li><a class="dropdown-item" href="{% url 'services:post_service' %}">Post Service</a></li>
                            {% endif %}

                            {% if user.profile %}
                                <li><a class="dropdown-item" href="{% url 'order:order_history' %}">Orders</a></li>
                                <li><a class="dropdown-item" href="{% url 'conversation:inbox' %}">Inbox</a></li>
                                <hr class="my-1">
                                <li><a class="dropdown-item" href="{% url 'view_profile' user.username %}">View Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'edit_profile' user.username %}">Edit Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                                <li><a class="dropdown-item" href="{% url 'account_delete' user.pk %}">Delete Account</a></li>
                                <hr class="my-1">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'order:order_history' %}">Orders</a></li>
                                <li><a class="dropdown-item" href="{% url 'conversation:inbox' %}">Inbox</a></li>
                                <hr class="my-1">
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                                <li><a class="dropdown-item" href="{% url 'account_delete' user.pk %}">Delete Account</a></li>
                                <hr class="my-1">
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            {% endif %}
                        </ul>
                        </li>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">
                        <i class="fas fa-shopping-cart"></i>
                    Cart</a>
                </li>
                    <a class="nav-link mx-2" href="{% url 'login' %}">Log in</a></li>
                    <a class="btn btn-primary fw-bold"role="button" href="{% url 'signup' %}">Sign Up</a>
                {% endif %}                
            </ul> 
        </div>
    </div>
</nav>

pages/templates/team.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Team
{% endblock %}

{% block content %}
    <div class = "d-flex justify-content-center row py-5 text-center">
        <h3>Meet Our Team</h3>
        <div class="bio-container my-3">
            <div class="bio-int-container d-block inline">
                <div class="bio-card">
                    <div class="card-front">
                        <img class = "img-thumbnail" src="{% static 'images/rob.jpg' %}" style = "height: 300px">
                    </div>
                    <div class="card-back">
                        <h5>Robbie Imperial</h5>
                        <p>Hey! :D My name is Rob, and I was tasked to do the cart and pages app, and most of the styling of the website! Looks nice doesn't it?</p>
                        <p>My hobbies include playing video games, reading and playing guitar.</p>
                        <p class = "linkedin-position">Visit my Linkedin: </p>
                    </div>
                </div>
                <a class="btn btn-primary mt-2"role="button" href="https://www.linkedin.com/in/imperial-robbie">Robbie Imperial</a>
            </div>

            <div class="bio-int-container d-block inline">
                <div class="bio-card">
                    <div class="card-front">
                        <img class = "img-thumbnail" src="{% static 'images/irene.jpg' %}" style = "height: 300px">
                    </div>

                    <div class="card-back">
                        <h5>Irene Ogbevoen</h5>
                        <p>Hi my name is Irene! :3 I was tasked to create the service and order apps on this website! I also created the different services available, hope you enjoy them!</p>
                        <p>My hobbies include playing video games, hanging out with my friends and baking.</p>
                        <p class = "linkedin-position">Visit my Linkedin: </p>
                    </div>
                </div>
                <a class="btn btn-primary mt-2"role="button" href="https://www.linkedin.com/in/irene-ogbevoen-1a36ba253">Irene Ogbevoen</a>
            </div>

            <div class="bio-int-container d-block inline">
                <div class="bio-card">
                    <div class="card-front">
                        <img class = "img-thumbnail" src="{% static 'images/ken.jpg' %}" style = "height: 300px">
                    </div>

                    <div class="card-back">
                        <h5>Keneith Atillo</h5>
                        <p>Hello! My name is Ken and I was tasked to create the accounts and search apps, and I did the majority of the testing! There are a few optional features I added too!</p>
                        <p>My hobbies include hanging with my mates, coding and playing video games.</p>
                        <p class = "linkedin-position">Visit my Linkedin: </p>
                    </div>
                </div>
                <a class="btn btn-primary mt-2"role="button" href="https://www.linkedin.com/in/keneithatillo">Keneith Atillo</a>
            </div>
        </div>
    </div>
{% endblock content %}