cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:service_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('full_remove/<uuid:service_id>/', views.full_remove, name='full_remove'),
]

conversations/urls.py
from django.urls import path
from .views import ConversationDeleteView, detail, inbox, new_conversation

app_name = 'conversation'

urlpatterns = [
    path('', inbox, name='inbox'),
    path('<int:pk>/', detail, name='conversation_detail'),
    path('new/<uuid:service_pk>/', new_conversation, name='new_conversation'),
    path('<int:pk>/delete/', ConversationDeleteView.as_view(), name='delete_conversation'),
]

servicehireproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('search/', include('search.urls')),
    path('orders/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('conversation/', include('conversations.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.service_list, name = 'all_services'),
    path('<uuid:category_id>/', views.service_list, name = 'services_by_category'),
    path('<uuid:category_id>/<uuid:service_id>/', views.service_detail, name = 'service_detail'),
    path('new/', views.ServiceCreateView.as_view(), name='post_service'),
    path('<uuid:service_id>/edit/', views.ServiceUpdateView.as_view(), name='edit_service'),
    path('<uuid:service_id>/delete/', views.ServiceDeleteView.as_view(), name='delete_service'),
    path('<uuid:service_id>/submit_review/', views.submit_review, name='submit_review'),
    path('provider/', views.provider_service_list, name = 'service_provider'),
]

services/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('services:services_by_category', args=[self.id])

    def __str__(self):
        return self.name

class Service(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    provider = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'service', blank=True)
    job_limit = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'service'
        verbose_name_plural = 'services'
    
    def get_absolute_url(self):
        return reverse('services:service_detail', args=[self.category.id, self.id])
    
    def __str__(self):
        return self.name
    
class Review(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(blank = True)
    rating = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)

    class Meta:
        ordering = ('subject',)
        verbose_name = 'review'
        verbose_name_plural = 'reviews'

    def __str__(self):
        return f"{self.subject} ({self.rating}) by {self.user}"

services/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['subject', 'rating', 'review']

services/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Avg
from .models import Category, Service, Review
from .forms import ReviewForm

class ServiceCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'services.add_service'
    model = Service
    template_name = 'service_new.html'
    fields = [
        'name',
        'description',
        'category',
        'price',
        'image',
        'job_limit',
        'available',
    ]

    def form_valid(self, form):
        form.instance.provider = self.request.user

        return super().form_valid(form)

def service_list(request, category_id=None):
    category = None
    services = Service.objects.filter(available=True)
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        services = Service.objects.filter(category=category, available=True)

    paginator = Paginator(services, 16)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        services = paginator.page(page)
    except (EmptyPage,InvalidPage):
        services = paginator.page(paginator.num_pages)

    return render(request, 'category.html',{'category':category, 'services':services})

def provider_service_list(request):
    category = None
    services = Service.objects.filter(provider=request.user)

    paginator = Paginator(services, 18)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        services = paginator.page(page)
    except (EmptyPage,InvalidPage):
        services = paginator.page(paginator.num_pages)

    return render(request, 'service_provider.html',{'category':category, 'services':services})


def service_detail(request, category_id, service_id):
    service = get_object_or_404(Service, category_id=category_id, id=service_id)
    reviews = service.review_set.all().order_by('-created')
    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 1)
    return render(request, 'service.html', {'service':service, 'reviews':reviews, 'average':average})

def submit_review(request, service_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = Review.objects.get(user=request.user, service_id=service_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        
        except Review.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = Review()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.service_id = service_id
                data.user = request.user
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)
        
class ServiceUpdateView(UpdateView):
    model = Service
    template_name = 'service_edit.html'
    fields = [
        'name',
        'description',
        'category',
        'price',
        'image',
        'job_limit',
        'available',
    ]
    pk_url_kwarg = 'service_id'

class ServiceDeleteView(DeleteView):
    model = Service
    template_name = 'service_delete.html'
    success_url = reverse_lazy('home')
    pk_url_kwarg = 'service_id'

services/templates/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}

{% endif %}

services/templates/category.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block metadescription %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        All Services
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div>
            <div class="container fw-bold mx-auto p-5">
                <p><a class="custom_a" href="{% url 'services:all_services' %}">All Services</a> | {{category.name}}</p>
            </div>
        </div>
        <div>
            <h1 class="text-center fw-bold">{{ category.name }}</h1>
            <p class="text-center">Browse our {{ category.name }} services</p>
            <br>
        </div>
    {% else %}
        <div class="p-5">
            <h1 class="text-center fw-bold p-5">All Services</h1>
        </div>
    {% endif %}
    <div class="container">
        <div class="row g-3 mx-auto">
            {% for service in services %}
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="card " id="service_card" style="height: 330px;">
                        <a class ="custom_link_text" href="{{service.get_absolute_url}}">
                        <img class="card-img-top w-100" style="height: 200px; object-fit: cover;" src="{{service.image.url}}" alt="{{service.name}}">
                        <div class="card-body text-center h-50">
                            <h4 class="fw-bold card-title">{{service.name}}</h4>
                            <p>€{{service.price | intcomma}}</p>
                            <p>By: {{service.provider}}</p>
                        </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if services.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in services.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if services.number == pg %}active{% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

services/templates/service.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block metadescription %}
    {{ service.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ service.name }} - Tenner
{% endblock %}
{% block content %}

    <div>
        <div class="container fw-bold mx-auto p-5">
            <p><a class="custom_a" href="{% url 'services:all_services' %}">All Services</a> | <a class="custom_a" href="{{ service.category.get_absolute_url }}">{{service.category}}</a> | {{ service.name }}</p>
        </div>
        <div class="container">
            <br>
            <div class="row">
                <div class="col-12 col-sm-12 co-md-12 col-lg-6 text-center">
                    <div style="min-width: 18rem;">
                        <img src="{{service.image.url}}" alt="{{service.name}}" class="img-thumbnail">
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 align-self-center">
                    <div class="card bg-white text-center p-5 align-items-center">
                        <h1>{{service.name}}</h1>
                        <p>€{{service.price | intcomma}}</p>
                        <p>{{service.description}}</p>
                        <p>By: <a class="custom_link_text" href="{% url 'view_profile' service.provider.username %}">{{service.provider}}</a></p>
                        <br>
                        {% if user == service.provider %}
                            <p><a class="btn btn-secondary" href="{% url 'services:edit_service' service.id %}">Edit Service</a></p>
                            <p><a class="btn btn-danger" href="{% url 'services:delete_service' service.id %}">Delete Service</a></p>
                        {% else %}
                            {% if service.job_limit == 0 %}
                                <p><b>Out of Stock</b></p>
                            {% else %}
                                <div class="d-inline-block">
                                    {% if user.is_authenticated %}
                                    <a class="btn btn-primary me-2" href="{% url 'cart:add_cart' service.id %}">Add to Cart</a>
                                    <a class="btn btn-primary ms-2" href="{% url 'conversation:new_conversation' service.id %}">Contact Provider</a>
                                    {% else %} 
                                    <a class="btn btn-primary me-2" href="{% url 'login' %}">Add to Cart</a>
                                    <a class="btn btn-primary ms-2" href="{% url 'login' %}">Contact Provider</a>
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endif %}
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class = 'container'>
            <div class = 'row'>
                {% if user != service.provider %}
                    <div class="card bg-white text-center p-5">
                        <h2 class="fw-bold">Post your review below</h2>
                        <br>
                        <form action="{% url 'services:submit_review' service.id %}" method="POST">
                            {% csrf_token %}
                            <label>How would you rate this service?</label>
                            <br>
                            <div class="rate">
                                <input type="radio" name="rating" id="rating5" value="5" required><label for="rating5" title="5"></label>
                                <input type="radio" name="rating" id="rating4" value="4" required><label for="rating4" title="4"></label>
                                <input type="radio" name="rating" id="rating3" value="3" required><label for="rating3" title="3"></label>
                                <input type="radio" name="rating" id="rating2" value="2" required><label for="rating2" title="2"></label>
                                <input type="radio" name="rating" id="rating1" value="1" required><label for="rating1" title="1"></label>
                            </div>
                            <br>

                            <div>
                                <p class="fw-bold">Subject:</p>
                                <input type="text" class="form-control" name="subject">
                                <br>
                                <p class="fw-bold">Description:</p>
                                <textarea name="review" class="form-control" rows="5"></textarea>
                                <br>
                                {% if user.is_authenticated %}
                                    <input type="submit" class="btn btn-primary d-block w-10 my-4" value="Post Review">
                                {% else %}
                                    <h2 class="fw-bold">Please <a class="custom_a" href="{% url 'login' %}">log in</a> to post a review.</h2>
                                {% endif %}
                            </div>
                        </form>
                        {% include 'alerts.html' %}
                    </div>
                {% endif %}
                <br>
                <div class="card bg-white text-center p-5">
                    <h2 class="fw-bold">Customer Reviews</h2>
                    <h5 class="fw-bold">Average Rating: {{ average }}</h5>
                </div>
                {% for review in reviews %}
                    <div class="card bg-white p-5">
                        <div class="col-6">
                            {% if review.user.profile.image %}
                                <a class="custom_link_text fw-bold" href="{% url 'view_profile' review.user.username %}"><img src="{{review.user.profile.image.url}}" alt="{{review.user}}" class="rounded-circle" width="50"></a>
                            {% else %}
                                <a class="custom_link_text fw-bold" href="{% url 'view_profile' review.user.username %}"><img src="{% static 'images/default_profile_pic.jpg' %}" alt="{{review.user}}" class="rounded-circle" width="50"></a>
                            {% endif %}
                            <p><a class="custom_link_text fw-bold" href="{% url 'view_profile' review.user.username %}">{{review.user}}</a></p>
                        </div>
                        <div class="col-6">
                            <h4>{{review.subject}}</h4>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                                </span>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

services/templates/service_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Service
{% endblock title %}

{% block content %}
<section class="py-5">
    <div class="container py-5">
        <div class="row mb-3">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="fw-bold">Delete Service</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 col-xl-6">
                <div class="card border-0">
                    <div class="card-body text-center d-flex flex-column align-items-center">
                        <form action="" method="post">{% csrf_token %}
                            <div class="alert alert-danger">
                                You are about to delete <b>{{ service.name }}</b> permanently.
                            </div>
                            <p>This process cannot be reverted. Are you sure you want continue?</p>
                            
                            <div class="mt-5"> 
                                <button class="btn btn-danger mx-3" type="submit">Delete Service</button>
                            <a href="{% url 'home' %}" type="button" class="btn btn-secondary mx-3">Cancel</a> 
                            </div>  
                        </form>           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

services/templates/service_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Service
{% endblock %}

{% block content %}
<section>
<div class="container py-5">
    <div class="row mb-4 mb-lg-5">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            <h2 class="fw-bold">Edit Service</h2>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-xl-4">
            <div class="card">
                <div class="card-body text-center d-flex flex-column align-items-center">
                    <form method="POST" enctype="multipart/form-data">
                        <p>
                            {% csrf_token %}
                            {{ form | crispy }}
                        </p>
                        <button type="submit" class="btn btn-primary d-block w-100 my-4">Save Changes</button>
                        <a href="{{ service.get_absolute_url }}" type="button" class="btn btn-secondary d-block w-100 my-4">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{% endblock content %}

services/templates/service_new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Add new service
{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container py-5">
        <div class="row mb-4 mb-lg-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <p class="fw-bold text-primary mb-2">Post Service</p>
                <h2 class="fw-bold">Post a new service</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 col-xl-6">
                <div class="card">
                    <div class="card-body d-flex flex-column align-items-center">
                        <form method="POST" enctype="multipart/form-data">
                            <p>
                                {{ form | crispy }}
                                {% csrf_token %}
                            </p>
                            <button type="submit" class="btn btn-primary d-block w-100 my-4">Post Service</button>
                            <a href="{% url 'home' %}" type="button" class="btn btn-secondary d-block w-100 my-4">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

services/templates/service_provider.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block metadescription %}
{% endblock %}
{% block title %}
    Your Services
{% endblock %}
{% block content %}
    <div class="p-5">
        <h1 class="text-center">Your Services</h1>
    </div>
    <div class="container">
        <div class="row g-3 mx-auto">
            {% for service in services %}
                {% if user == service.provider %}
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="card text-center" id="service_card" style="height: 330px;">
                            <a class ="custom_link_text" href="{{service.get_absolute_url}}">
                            <img class="card-img-top w-100" style="height: 200px; object-fit: cover;" src="{{service.image.url}}" alt="{{service.name}}">
                            <div class="card-body h-50">
                                <h4 class="fw-bold card-title">{{service.name}}</h4>
                                <p>€{{service.price | intcomma}}</p>
                                <p>By: {{service.provider}}</p>
                            </div>
                            </a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if services.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in services.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if services.number == pg %}active{% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}