cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:service_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('full_remove/<uuid:service_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.orderDetail.as_view(), name='order_detail'),
]

servicehireproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('search/', include('search.urls')),
    path('orders/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('conversation/', include('conversations.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.service_list, name = 'all_services'),
    path('<uuid:category_id>/', views.service_list, name = 'services_by_category'),
    path('<uuid:category_id>/<uuid:service_id>/', views.service_detail, name = 'service_detail'),
    path('new/', views.ServiceCreateView.as_view(), name='post_service'),
    path('<uuid:service_id>/edit/', views.ServiceUpdateView.as_view(), name='edit_service'),
    path('<uuid:service_id>/delete/', views.ServiceDeleteView.as_view(), name='delete_service'),
    path('<uuid:service_id>/submit_review/', views.submit_review, name='submit_review'),
    path('provider/', views.provider_service_list, name = 'service_provider'),
]

order/models.py
from django.db import models

class Order(models.Model):
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Euro Order Total')
    emailAddress = models.EmailField(max_length=250, blank=True, verbose_name='Email Address')
    created = models.DateTimeField(auto_now_add=True)
    billingName = models.CharField(max_length=250, blank=True)
    billingAddress1 = models.CharField(max_length=250, blank=True)
    billingCity = models.CharField(max_length=250, blank=True)
    billingPostcode = models.CharField(max_length=10, blank=True)
    billingCountry = models.CharField(max_length=200, blank=True)

    class Meta:
        db_table = 'Order'
        ordering = ['-created']

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    service = models.CharField(max_length=250)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Euro Price')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    class Meta:
        db_table = 'OrderItem'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.service

order/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderItem
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

def thanks(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)
    return render(request, 'thanks.html',{'customer_order': customer_order}) 


class orderHistory(LoginRequiredMixin, View):
    def get (self, request):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order_details = Order.objects.filter(emailAddress=email)
        return render(request, 'order/orders_list.html', {'order_details': order_details})

class orderDetail(LoginRequiredMixin, View):
    def get(self, request, order_id):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order = Order.objects.get(id=order_id, emailAddress=email)
            order_items = OrderItem.objects.filter(order=order)

        return render(request, 'order/order_detail.html', {'order': order, 'order_items': order_items})

order/templates/order/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Order Details - Tenner
{% endblock %}
{% block content %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">Order Details</h1>
        <br>
        <table class="table table-bordered">
            <tr>
                <td class="text-left p-5" colspan="4">
                    <b>Order: </b>#{{ order.id }}<br>
                    <b>Date: </b>{{ order.created|date:"d M Y" }}<br>
                    <b>Order Total: </b>€{{ order.total }}<br>
                    <b>Order Status: </b><i class="fas fa-check"></i>
                </td>
            </tr>
            <tr>
                <td><b>Product Description</b></td>
                <td><b>Qty</b></td>
                <td><b>Unit Price</b></td>
            </tr>
            {% for item in order_items %}
            <tr>
                <td>{{ item.service }}</td>
                <td>{{ item.quantity }}</td>
                <td>€{{ item.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td><br></td>
                <td><b>Total</b></td>
                <td>€{{ order.total }}</td>
            </tr>
            <tr>
                <td class="text-left" colspan="2">
                    <b>Payment Details: </b><br>
                    The order #{{ order.id }} has been paid successfully via Stripe.
                </td>
                <td class="text-left" colspan="2">
                    <b>Billing Address: </b><br>
                    {{ order.billingName }}<br>
                    {{ order.billingAddress1 }}<br>
                    {{ order.billingCity }}<br>
                    {{ order.billingPostcode }}<br>
                    {{ order.billingCountry }}<br>
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock content %}

order/templates/order/orders_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Order History - Tenner
{% endblock %}
{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center">Order History</h1>
            <br>
            {% if order_details %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in order_details %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.created|date:"d M Y" }}</td>
                        <td>{{ order.total }}</td>
                        <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                        <td><a href="{% url 'order:order_detail' order.id %}">View order</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>You have not placed any orders yet.<br><br><a href="{% url 'services:all_services' %}" class="btn btn-primary">Continue shopping</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <br>
{% endblock %}