cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:service_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('full_remove/<uuid:service_id>/', views.full_remove, name='full_remove'),
]

servicehireproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('search/', include('search.urls')),
    path('orders/', include('order.urls')),
    path('cart/', include('cart.urls')),
    path('conversation/', include('conversations.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.service_list, name = 'all_services'),
    path('<uuid:category_id>/', views.service_list, name = 'services_by_category'),
    path('<uuid:category_id>/<uuid:service_id>/', views.service_detail, name = 'service_detail'),
    path('new/', views.ServiceCreateView.as_view(), name='post_service'),
    path('<uuid:service_id>/edit/', views.ServiceUpdateView.as_view(), name='edit_service'),
    path('<uuid:service_id>/delete/', views.ServiceDeleteView.as_view(), name='delete_service'),
    path('<uuid:service_id>/submit_review/', views.submit_review, name='submit_review'),
    path('provider/', views.provider_service_list, name = 'service_provider'),
]

cart/models.py
from django.db import models
from services.models import Service

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.service.price * self.quantity

    def __str__(self):
        return self.service

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404
from services.models import Service 
from .models import Cart, CartItem 
from order.models import Order, OrderItem
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
import stripe 

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart 

def add_cart(request, service_id):
    service = Service.objects.get(id=service_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save() 
    try:
        cart_item = CartItem.objects.get(service=service, cart=cart)
        if cart_item.quantity < cart_item.service.job_limit:
            cart_item.quantity += 1 
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(service=service, quantity = 1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.service.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    stripe.api_key = settings.STRIPE_SECRET_KEY 
    stripe_total = int(total*100)
    description = 'Tenner | Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY 
    if request.method=='POST':
        print(request.POST)
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billingName = request.POST['stripeBillingName']
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingcity = request.POST['stripeBillingAddressCity']
            billingCountry = request.POST['stripeBillingAddressCountryCode']

            customer = stripe.Customer.create(email=email, source=token)
            stripe.Charge.create(amount=stripe_total,
            currency="eur",
            description=description,
            customer=customer.id)
            try:
                order_details = Order.objects.create(
                    token = token,
                    total = total,
                    emailAddress = email,
                    billingName = billingName,
                    billingAddress1 = billingAddress1,
                    billingCity = billingcity,
                    billingCountry = billingCountry,
                )
                order_details.save()
                for order_item in cart_items:
                    oi = OrderItem.objects.create(
                        service = order_item.service.name,
                        quantity = order_item.quantity,
                        price = order_item.service.price,
                        order = order_details)
                    oi.save
                    services = Service.objects.get(id=order_item.service.id)
                    services.job_limit = int(order_item.service.job_limit - order_item.quantity)
                    services.save()
                    order_item.delete()
                    print('The order has been created')
                return redirect ('order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass

        except stripe.error.CardError as e:
            return e
    return render(request, 'cart.html', {'cart_items':cart_items, 'total':total, 'counter':counter,
    'data_key':data_key, 'stripe_total':stripe_total,
    'description':description})

def full_remove(request, service_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    service = get_object_or_404(Service, id=service_id)
    cart_item = CartItem.objects.get(service=service, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your Cart
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your cart is empty
                </h1>
                <br>
                <p class="text-center">
                    Please click <a class = "link-violet" href="{% url 'services:all_services' %}">here</a> to continue browsing our services.
                </p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    Your Cart
                </h1>
                <br>
            </div>
        </div>

        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">
                                Your Services
                            </th>
                        </tr>   
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{cart_item.service.get_url}}"><img src="{{cart_item.service.image.url}}" 
                                     alt="" class="float-left rounded custom_image"></a>
                                </td>
                                <td class="text-left">
                                    {{cart_item.service.name}}
                                </td>
                                <td>
                                    €{{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.service.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.service.id %}" class="custom_a"><i class="fas fa-plus-circle  
                                           custom_icon"></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.service.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.service.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                                    </td>
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your cart items before proceeding with your order(s).
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your total is: <strong>€{{ total }}</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <form action="" method="POST">
                    {% csrf_token %}
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="{{ data_key }}"
                            data-amount="{{ stripe_total }}"
                            data-name="Tenner"
                            data-description="{{ description }}"
                            data-image="{% static 'images/trolley.jpg' %}"
                            data-locale="auto"
                            data-currency="eur"
                            data-shipping-address="false"
                            data-billing-address="true"
                            data-zip-code="true">
                         </script>
                </form>                    
                <div class="mx-auto">
                    <a href="{% url 'services:all_services' %}" class="btn btn-secondary btn-block 
                     my_custom_button">Continue 
                    Browsing Services</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}
{% endblock %}